AWSTemplateFormatVersion: "2010-09-09"
Description: Glue and Lambda resources for PROD environment

Resources:

  ProdGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: prod-sample-glue-job
      Role: arn:aws:iam::814724283102:role/AWSGlueServiceRoleDefault
      Command:
        Name: glueetl
        ScriptLocation: s3://aws-data-engineering-ci-artifacts/artifacts/glue/sample_glue_job.py
        PythonVersion: "3"
      GlueVersion: "4.0"
      MaxCapacity: 5.0

  ProdLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: prod-sample-lambda
      Runtime: python3.9
      Role: arn:aws:iam::814724283102:role/service-role/lambda-basic-execution
      Handler: sample_lambda.lambda_handler
      Code:
        S3Bucket: aws-data-engineering-ci-artifacts
        S3Key: artifacts/lambda/sample_lambda.py
      Timeout: 120
      MemorySize: 256
