version: 0.2

phases:
  build:
    commands:
      - echo "WORKDIR:"
      - pwd
      - echo "FILES:"
      - ls -R

      - mkdir -p artifacts/glue artifacts/lambda

      - echo "Finding Glue job"
      - |
        GLUE_FILE=$(find . -name "sample_glue_job.py" | head -n 1)
        echo "Glue file: $GLUE_FILE"
        [ -z "$GLUE_FILE" ] && exit 1
        cp "$GLUE_FILE" artifacts/glue/

      - echo "Finding Lambda file"
      - |
        LAMBDA_FILE=$(find . -name "sample_lambda.py" | head -n 1)
        echo "Lambda file: $LAMBDA_FILE"
        [ -z "$LAMBDA_FILE" ] && exit 1
        zip -j artifacts/lambda/sample_lambda.zip "$LAMBDA_FILE"

artifacts:
  base-directory: artifacts
  files:
    - "**/*"
